//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartBeatPortal.MultiResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Multi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeartBeatPortal.MultiResources.Multi", typeof(Multi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select timeline and diagram type.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Servers.
        /// </summary>
        public static string AllServer {
            get {
                return ResourceManager.GetString("AllServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count.
        /// </summary>
        public static string AverageCount {
            get {
                return ResourceManager.GetString("AverageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 1 hour).
        /// </summary>
        public static string AverageCount1 {
            get {
                return ResourceManager.GetString("AverageCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 10 minutes).
        /// </summary>
        public static string AverageCount10 {
            get {
                return ResourceManager.GetString("AverageCount10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 12 hours).
        /// </summary>
        public static string AverageCount12 {
            get {
                return ResourceManager.GetString("AverageCount12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 15 days).
        /// </summary>
        public static string AverageCount15day {
            get {
                return ResourceManager.GetString("AverageCount15day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 2 hours).
        /// </summary>
        public static string AverageCount2 {
            get {
                return ResourceManager.GetString("AverageCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 24 hours).
        /// </summary>
        public static string AverageCount24 {
            get {
                return ResourceManager.GetString("AverageCount24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 2 days).
        /// </summary>
        public static string AverageCount2day {
            get {
                return ResourceManager.GetString("AverageCount2day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 30 days).
        /// </summary>
        public static string AverageCount30day {
            get {
                return ResourceManager.GetString("AverageCount30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 6 hours).
        /// </summary>
        public static string AverageCount6 {
            get {
                return ResourceManager.GetString("AverageCount6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Execution Count (Last 7 days).
        /// </summary>
        public static string AverageCount7day {
            get {
                return ResourceManager.GetString("AverageCount7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration.
        /// </summary>
        public static string AverageDuration {
            get {
                return ResourceManager.GetString("AverageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 1 hour).
        /// </summary>
        public static string AverageDuration1 {
            get {
                return ResourceManager.GetString("AverageDuration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 10 minutes).
        /// </summary>
        public static string AverageDuration10 {
            get {
                return ResourceManager.GetString("AverageDuration10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 12 hours).
        /// </summary>
        public static string AverageDuration12 {
            get {
                return ResourceManager.GetString("AverageDuration12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 15 days).
        /// </summary>
        public static string AverageDuration15day {
            get {
                return ResourceManager.GetString("AverageDuration15day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 2 hours).
        /// </summary>
        public static string AverageDuration2 {
            get {
                return ResourceManager.GetString("AverageDuration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 24 hours).
        /// </summary>
        public static string AverageDuration24 {
            get {
                return ResourceManager.GetString("AverageDuration24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 2 days).
        /// </summary>
        public static string AverageDuration2day {
            get {
                return ResourceManager.GetString("AverageDuration2day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 30 days).
        /// </summary>
        public static string AverageDuration30day {
            get {
                return ResourceManager.GetString("AverageDuration30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 6 hours).
        /// </summary>
        public static string AverageDuration6 {
            get {
                return ResourceManager.GetString("AverageDuration6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (Last 7 days).
        /// </summary>
        public static string AverageDuration7day {
            get {
                return ResourceManager.GetString("AverageDuration7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration (milliseconds).
        /// </summary>
        public static string AverageDurationMilli {
            get {
                return ResourceManager.GetString("AverageDurationMilli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 1 hour).
        /// </summary>
        public static string AverageLoad1 {
            get {
                return ResourceManager.GetString("AverageLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 10 minutes).
        /// </summary>
        public static string AverageLoad10 {
            get {
                return ResourceManager.GetString("AverageLoad10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 12 hours).
        /// </summary>
        public static string AverageLoad12 {
            get {
                return ResourceManager.GetString("AverageLoad12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 15 days).
        /// </summary>
        public static string AverageLoad15day {
            get {
                return ResourceManager.GetString("AverageLoad15day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 2 hours).
        /// </summary>
        public static string AverageLoad2 {
            get {
                return ResourceManager.GetString("AverageLoad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 24 hours).
        /// </summary>
        public static string AverageLoad24 {
            get {
                return ResourceManager.GetString("AverageLoad24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 2 days).
        /// </summary>
        public static string AverageLoad2day {
            get {
                return ResourceManager.GetString("AverageLoad2day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 30 days).
        /// </summary>
        public static string AverageLoad30day {
            get {
                return ResourceManager.GetString("AverageLoad30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 6 hours).
        /// </summary>
        public static string AverageLoad6 {
            get {
                return ResourceManager.GetString("AverageLoad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (Last 7 days).
        /// </summary>
        public static string AverageLoad7day {
            get {
                return ResourceManager.GetString("AverageLoad7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Load (milliseconds).
        /// </summary>
        public static string AverageLoadmilli {
            get {
                return ResourceManager.GetString("AverageLoadmilli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 1 hour).
        /// </summary>
        public static string AverageStart1 {
            get {
                return ResourceManager.GetString("AverageStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 10 minutes).
        /// </summary>
        public static string AverageStart10 {
            get {
                return ResourceManager.GetString("AverageStart10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 12 hours).
        /// </summary>
        public static string AverageStart12 {
            get {
                return ResourceManager.GetString("AverageStart12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 15 days).
        /// </summary>
        public static string AverageStart15day {
            get {
                return ResourceManager.GetString("AverageStart15day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 2 hours).
        /// </summary>
        public static string AverageStart2 {
            get {
                return ResourceManager.GetString("AverageStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 24 hours).
        /// </summary>
        public static string AverageStart24 {
            get {
                return ResourceManager.GetString("AverageStart24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 2 days).
        /// </summary>
        public static string AverageStart2day {
            get {
                return ResourceManager.GetString("AverageStart2day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 30 days).
        /// </summary>
        public static string AverageStart30day {
            get {
                return ResourceManager.GetString("AverageStart30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 6 hours).
        /// </summary>
        public static string AverageStart6 {
            get {
                return ResourceManager.GetString("AverageStart6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration vs. Start Time (Last 7 days).
        /// </summary>
        public static string AverageStart7day {
            get {
                return ResourceManager.GetString("AverageStart7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 1 hour).
        /// </summary>
        public static string CountStart1 {
            get {
                return ResourceManager.GetString("CountStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 10 minutes).
        /// </summary>
        public static string CountStart10 {
            get {
                return ResourceManager.GetString("CountStart10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 12 hours).
        /// </summary>
        public static string CountStart12 {
            get {
                return ResourceManager.GetString("CountStart12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 15 days).
        /// </summary>
        public static string CountStart15day {
            get {
                return ResourceManager.GetString("CountStart15day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 2 hours).
        /// </summary>
        public static string CountStart2 {
            get {
                return ResourceManager.GetString("CountStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 24 hours).
        /// </summary>
        public static string CountStart24 {
            get {
                return ResourceManager.GetString("CountStart24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 2 days).
        /// </summary>
        public static string CountStart2day {
            get {
                return ResourceManager.GetString("CountStart2day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 30 days).
        /// </summary>
        public static string CountStart30day {
            get {
                return ResourceManager.GetString("CountStart30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 6 hours).
        /// </summary>
        public static string CountStart6 {
            get {
                return ResourceManager.GetString("CountStart6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count vs. Start Time (Last 7 days).
        /// </summary>
        public static string CountStart7day {
            get {
                return ResourceManager.GetString("CountStart7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed To.
        /// </summary>
        public static string Deployed {
            get {
                return ResourceManager.GetString("Deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Type.
        /// </summary>
        public static string Diag {
            get {
                return ResourceManager.GetString("Diag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (ms).
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Count.
        /// </summary>
        public static string ExeCount {
            get {
                return ResourceManager.GetString("ExeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Count.
        /// </summary>
        public static string ExpCount {
            get {
                return ResourceManager.GetString("ExpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Execution.
        /// </summary>
        public static string FirstExe {
            get {
                return ResourceManager.GetString("FirstExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Heartbeat.
        /// </summary>
        public static string FirstHeart {
            get {
                return ResourceManager.GetString("FirstHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 1 hour (per 10 minutes).
        /// </summary>
        public static string Last1 {
            get {
                return ResourceManager.GetString("Last1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 10 minutes (per minute).
        /// </summary>
        public static string Last10 {
            get {
                return ResourceManager.GetString("Last10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 12 hours (per hour).
        /// </summary>
        public static string Last12 {
            get {
                return ResourceManager.GetString("Last12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 15 days (per day).
        /// </summary>
        public static string Last15day {
            get {
                return ResourceManager.GetString("Last15day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 2 hours (per 10 minutes).
        /// </summary>
        public static string Last2 {
            get {
                return ResourceManager.GetString("Last2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24 hours (per hour).
        /// </summary>
        public static string Last24 {
            get {
                return ResourceManager.GetString("Last24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 2 days (per 2 hours).
        /// </summary>
        public static string Last2day {
            get {
                return ResourceManager.GetString("Last2day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days (per day).
        /// </summary>
        public static string Last30day {
            get {
                return ResourceManager.GetString("Last30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 hous (per 30 minutes).
        /// </summary>
        public static string Last6 {
            get {
                return ResourceManager.GetString("Last6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days (per day).
        /// </summary>
        public static string Last7day {
            get {
                return ResourceManager.GetString("Last7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Execution.
        /// </summary>
        public static string LastExe {
            get {
                return ResourceManager.GetString("LastExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Heartbeat.
        /// </summary>
        public static string LastHeart {
            get {
                return ResourceManager.GetString("LastHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load (milliseconds).
        /// </summary>
        public static string Loadmilli {
            get {
                return ResourceManager.GetString("Loadmilli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 1 hour).
        /// </summary>
        public static string LoadStart1 {
            get {
                return ResourceManager.GetString("LoadStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 10 minutes).
        /// </summary>
        public static string LoadStart10 {
            get {
                return ResourceManager.GetString("LoadStart10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 12 hours).
        /// </summary>
        public static string LoadStart12 {
            get {
                return ResourceManager.GetString("LoadStart12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 15 days).
        /// </summary>
        public static string LoadStart15day {
            get {
                return ResourceManager.GetString("LoadStart15day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 2 hours).
        /// </summary>
        public static string LoadStart2 {
            get {
                return ResourceManager.GetString("LoadStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 24 hours).
        /// </summary>
        public static string LoadStart24 {
            get {
                return ResourceManager.GetString("LoadStart24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 2 days).
        /// </summary>
        public static string LoadStart2day {
            get {
                return ResourceManager.GetString("LoadStart2day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 30 days).
        /// </summary>
        public static string LoadStart30day {
            get {
                return ResourceManager.GetString("LoadStart30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 6 hours).
        /// </summary>
        public static string LoadStart6 {
            get {
                return ResourceManager.GetString("LoadStart6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load vs. Start Time (Last 7 days).
        /// </summary>
        public static string LoadStart7day {
            get {
                return ResourceManager.GetString("LoadStart7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Duration (ms).
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Info.
        /// </summary>
        public static string MethodInfo {
            get {
                return ResourceManager.GetString("MethodInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method List.
        /// </summary>
        public static string MethodList {
            get {
                return ResourceManager.GetString("MethodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Load.
        /// </summary>
        public static string MethodLoad {
            get {
                return ResourceManager.GetString("MethodLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Name.
        /// </summary>
        public static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Duration (ms).
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Average duration (ms).
        /// </summary>
        public static string OverallAverage {
            get {
                return ResourceManager.GetString("OverallAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooredoo Support Portal.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Info.
        /// </summary>
        public static string ServerInfo {
            get {
                return ResourceManager.GetString("ServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Info.
        /// </summary>
        public static string ServiceInfo {
            get {
                return ResourceManager.GetString("ServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service List.
        /// </summary>
        public static string ServiceList {
            get {
                return ResourceManager.GetString("ServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 Hourly Average Durations For Today.
        /// </summary>
        public static string Top10Duration {
            get {
                return ResourceManager.GetString("Top10Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 Hourly Execution Counts For Today.
        /// </summary>
        public static string Top10Exe {
            get {
                return ResourceManager.GetString("Top10Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 50 Method Loads.
        /// </summary>
        public static string Top50 {
            get {
                return ResourceManager.GetString("Top50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Execution Count.
        /// </summary>
        public static string TotalExe {
            get {
                return ResourceManager.GetString("TotalExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
    }
}
